global:
  scrape_interval: 15s  # 기본 스크래핑 주기
  evaluation_interval: 15s  # 알림 규칙 평가 주기

scrape_configs:
  # Prometheus 서버 자신 스크래핑
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot 애플리케이션 스크래핑
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']